language: node_js
node_js:
  - "4"
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database student_dashboard_test;' -U postgres
env:
  - NODE_ENV=test
  - DATABASE_URL=postgres://localhost/student_dashboard_test
  - CAS_BASE_URL=https://cas
